AWSTemplateFormatVersion: '2010-09-09'
Description: Public and private route tables

Resources:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue VPCId
      Tags:
        - Key: name
          Value: pub-route-table

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue VPCId
      Tags:
        - Key: name
          Value: priv-route-table

Outputs:
  PublicRouteTableId:
    Value: !Ref PublicRouteTable
    Export:
      Name: PublicRouteTableId

  PrivateRouteTableId:
    Value: !Ref PrivateRouteTable
    Export:
      Name: PrivateRouteTableId
